#+TITLE: Configuration Specific To Mesiniaga's Lenovo Thinkpad E420
#+STARTUP: indent hidestars
#+OPTIONS: toc:nil num:nil ^:nil

So this is basically the configuration file for munchkin, my work laptop.

It's /way/ beefier than my netbook, but it isn't mine.

* Before we begin
Anyway, as with all hostname-specific machines, this little fella runs the following code to load the common features I expect from all my emacs instances:

#+begin_src emacs-lisp
(org-babel-load-file (expand-file-name "tariqk-common.org" starter-kit-dir))
#+end_src

* What goes in here
Settings for emacs specific to a laptop , running Windows 7, Enterprise Edition.

* The Settings themselves
Actual settings go here.

The goals of these settings is to:
- Minimize eye strain.
- Work seamlessly with Windows, or as well as it can anyway.
- Be modular, so that I can take this out quickly in the event the system needs to be returned or reformatted.

** Custom faces
There is obviously no DejaVu Mono Sans installed in Windows by default, so we use Windows 7's default font, Consolas, which is decent.

#+begin_src emacs-lisp
(custom-set-faces
'(default ((t (:foundry "outline" :family "Consolas" :height 100)))))
#+end_src

** Custom variables
Instead of using the =customize= option to fix stuff (which saves it in =customize.el= and doesn't get propagated to the github repo, I save them here.

*** Quirks-fixing
Of course, there are a whole bunch of little quirks that emacs for w32 has. When I find one, I fix it here.

#+BEGIN_SRC emacs-lisp :noweb yes
(custom-set-variables
<<quirks-custom-variables-flyspell>>
)
#+END_SRC

**** Fixing flyspell on Windows.
=flyspell= don't work normally with this variant of emacs, so we need to install it into the system and get Windows to link it here.

#+NAME: quirks-custom-variables-flyspell
#+BEGIN_SRC emacs-lisp
   '(ispell-dictionary "british")
   '(ispell-program-name "C:\\Program Files \(x86\)\\Aspell\\bin\\aspell.exe")
#+END_SRC
**** Fixing the default directory for find-file
So it turns out that the default directory for =find-file= is somewhere in the emacs application directory. How annoying! Let's fix that.

#+BEGIN_SRC emacs-lisp
  (setq default-directory "~")
#+END_SRC

** Window Setup The Way I Like It (Here)
Basically, let's keep it transparent, and let's put in a color scheme. We'll do the color scheme after everything is sorted out.

And once that's all done, just maximize the window, w32-style. And maybe load dired?

#+begin_src emacs-lisp
  (transparent 80 80)
  (require 'color-theme)
  (eval-after-load "color-theme"
    '(progn
       (color-theme-initialize)
       (color-theme-dark-laptop)))
  (w32-send-sys-command 61488)
  (dired "~/Documents/Projects")
#+end_src
