#+TITLE: Configuration Specific To Work Laptops
#+STARTUP: indent hidestars
#+OPTIONS: toc:nil num:nil ^:nil
#+PROPERTY: header-args :results silent :colnames yes

So this is basically the configuration file for my work machines, which are Windows laptops.

It's pretty spiffy and new, it has a whole bunch of weird Windows hacks to make it work properly, and I don't ultimately own it.

* Before we begin
Anyway, as with all hostname-specific machines, this little fella runs the following code to load the common features I expect from all my emacs instances:

#+begin_src emacs-lisp
(org-babel-load-file (expand-file-name "tariqk-common.org" starter-kit-dir))
#+end_src

* Download some pre-requisites
Now, the common-files should have done the following:

- Loaded the compulsory modules that are common to all machines
- Populated the =package-pinned-packages= variables.

But that's for what's common in all machines. These are the packages that need to be installed on friend desktop:

#+NAME: package-settings
| name       | repository |
|------------+------------|
| everything | marmalade  |
| ssh-agency | MELPA      |

#+begin_src emacs-lisp :var name=package-settings[,0] repository=package-settings[,1]
  (when (require 'package nil 'noerror)
    (when (require 'cl nil 'noerror)
      (lexical-let ((pkgs (mapcar #'intern name))
                    (original))
        (setq original package-pinned-packages)
        (setq package-pinned-packages (append original (pairlis pkgs repository)))
        (apply 'starter-kit-install-if-needed pkgs))
        (package-initialize)))
#+end_src  

* What goes in here
Settings for emacs specific to a laptop , running Windows 7, Enterprise Edition.

* The Settings themselves
Actual settings go here.

The goals of these settings is to:
- Minimize eye strain.
- Work seamlessly with Windows, or as well as it can anyway.
- Be modular, so that I can take this out quickly in the event the system needs to be returned or reformatted.

** Custom faces
There is obviously no DejaVu Mono Sans installed in Windows by default, so we use Windows 7's default font, Consolas, which is decent.

#+begin_src emacs-lisp
(custom-set-faces
'(default ((t (:foundry "outline" :family "Consolas" :height 100)))))
#+end_src

** Custom variables
Instead of using the =customize= option to fix stuff (which saves it in =customize.el= and doesn't get propagated to the github repo, I save them here.

*** Local Setup
***** Link to all work =.org= files.
Right now, all work =.org= files are scattered, but under a folder backed up by company cloud storage (presumably, if and when I move, they'll be placed in an archive file for easy access), and likely on work-specific machines.

A major issue right now is that every time the files are reloaded, the search time is /interminable/. There is a [[http://stackoverflow.com/a/17232509/800892][solution]] for this problem, but it requires more thinking than I'm able to do right now, and, also, will write an external file.
#+BEGIN_SRC emacs-lisp
  (load-library "find-lisp")
  (setq org-agenda-files (append org-agenda-files (find-lisp-find-files "~/Dropbox (STI)/" "\.org$")))
#+END_SRC
***** Ibuffer Settings
As a consequence of loading /all/ those org files, Emacs now has several hundred buffer loaded at the same time LMAO.

But guess what? It turns out that Ibuffer does a /great/ job at grouping these buffers, but it's just poorly documented. But [[http://martinowen.net/blog/2010/02/03/tips-for-emacs-ibuffer.html][there's a blog post for it]]!

Here are some of thqe local buffer settings:
#+BEGIN_SRC emacs-lisp
  (setq ibuffer-saved-filter-groups
        '(("work laptop"
           ("Work Org Files" (filename . "Dropbox (STI)/.+\.org$"))
           ("Personal Org Files" (filename . "private-org-files/agendas/.+\.org$"))
           ("File Folders" (mode . dired-mode))
           ("Emacs" (or (name . "\*scratch\*")
                        (name . "\*Messages\*")))
           ("Help" (or (name . "\*Help\*")
                       (name . "\*Apropos\*")
                       (name . "\*Info\*")))
           ("Magit" (name . "\*magit")))))

  (add-hook 'ibuffer-mode-hook
            '(lambda ()
               (ibuffer-switch-to-saved-filter-groups "work laptop")))
#+END_SRC

Also, here are some other miscellaneous options for Ibuffer that will help things out:

#+BEGIN_SRC emacs-lisp
  (add-hook 'ibuffer-mode-hook
            '(lambda ()
               (ibuffer-auto-mode t)))
  (setq ibuffer-expert t)
  (setq ibuffer-show-empty-filter-groups nil)
#+END_SRC


*** Quirks-fixing
Of course, there are a whole bunch of little quirks that emacs for w32 has. When I find one, I fix it here.

#+BEGIN_SRC emacs-lisp :noweb yes
(custom-set-variables
<<quirks-custom-variables-flyspell>>
<<quirks-custom-variables-everything>>
)
#+END_SRC

**** Fixing =flyspell= on Windows.
=flyspell= don't work normally with this variant of emacs, so we need to install it into the system and get Windows to link it here.

#+NAME: quirks-custom-variables-flyspell
#+BEGIN_SRC emacs-lisp
   '(ispell-dictionary "british")
   '(ispell-program-name "C:\\Program Files \(x86\)\\Aspell\\bin\\aspell.exe")
#+END_SRC
**** Fixing the default directory for =find-file=
So it turns out that the default directory for =find-file= is somewhere in the emacs application directory. How annoying! Let's fix that.

#+BEGIN_SRC emacs-lisp
  (setq default-directory "~")
#+END_SRC
**** Pointing =everything= to the right executable
The original =es.exe= file location is hard-coded, and /egregiously/ wrong in this current setup. Here's where it should be:

#+NAME: quirks-custom-variables-everything
#+begin_src emacs-lisp
  '(everything-cmd "C:\\Program Files\\Everything\\es.exe")
#+end_src
**** Allowing =magit= to work properly
So, based on [[http://emacs.stackexchange.com/questions/177/magit-on-windows-searching-for-program-permission-denied-git][this solution]], we need to locate =git= manually for =magit= to work. Therefore:

#+begin_src emacs-lisp
  (add-to-list 'exec-path "C:/Program Files/Git/bin")
#+end_src

And, as a first step to solve the whole =git= failing in general to push, from [[https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows][here]]:
#+begin_src emacs-lisp
  (setenv "SSH_ASKPASS" "git-gui--askpass")
#+end_src

Additional note: no, it didn't work, so I'm using [[https://help.github.com/articles/generating-ssh-keys/][this solution]]. Step 3 doesn't work, so I ended up using =eval $(ssh-agent)= instead and that works, based on [[http://stackoverflow.com/a/21909432][this answer]].
** Window Setup The Way I Like It (Here)
Basically, let's keep it transparent, and let's put in a color scheme. We'll do the color scheme after everything is sorted out.

And once that's all done, just maximize the window, w32-style. And maybe load dired?

#+begin_src emacs-lisp
  (*hx-transparent 80 80)
  (when (require 'color-theme nil 'noerror)
      (eval-after-load "color-theme"
        '(progn
           (color-theme-initialize)
           (color-theme-dark-laptop))))
  (dired "~/Dropbox (STI)/Projects")
  (toggle-frame-maximized)
#+end_src
